series: Basic C++
title: Inheritance
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Inheritance can be used to avoid rewriting code.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Constructors and Destructors